window.__LAW_APP_TEST_DATA = {
  "version": "1.0.0",
  "timestamp": "2026-04-22T09:10:00.000Z",
  "data": {
    "clients": [
      {
        "id": 1,
        "name": "أحمد علي عبد المقصود",
        "address": "15 شارع التحرير، طنطا، الغربية",
        "phone": "01010001001"
      },
      {
        "id": 2,
        "name": "منة الله محمد السيد",
        "address": "8 شارع الاستاد، كفر الشيخ",
        "phone": "01120002002"
      },
      {
        "id": 3,
        "name": "محمود السيد عبد الله",
        "address": "الحي العاشر، العاشر من رمضان، الشرقية",
        "phone": "01030003003"
      },
      {
        "id": 4,
        "name": "سارة محمود عادل",
        "address": "22 شارع الجامعة، المنصورة",
        "phone": "01240004004"
      },
      {
        "id": 5,
        "name": "محمد فوزي إبراهيم",
        "address": "1 شارع الجيش، الإسماعيلية",
        "phone": "01050005005"
      },
      {
        "id": 6,
        "name": "ياسمين حسن عبد الرحمن",
        "address": "9 شارع البحر، بورسعيد",
        "phone": "01060006006"
      },
      {
        "id": 7,
        "name": "أحمد سالم عزالدين محمود",
        "address": "10 شارع النصر، مدينة نصر، القاهرة",
        "phone": "01070007007"
      },
      {
        "id": 8,
        "name": "حسام عبد الفتاح عبد الله",
        "address": "12 شارع صلاح سالم، شبرا، القاهرة",
        "phone": "01080008008"
      },
      {
        "id": 9,
        "name": "دينا إبراهيم محمد",
        "address": "5 شارع القنال، الزقازيق، الشرقية",
        "phone": "01090009009"
      }
    ],
    "opponents": [
      {
        "id": 1,
        "name": "شركة الأفق للاستثمار العقاري",
        "address": "برج النيل، المعادي، القاهرة",
        "phone": "0225559001"
      },
      {
        "id": 2,
        "name": "سعيد محمود العطار",
        "address": "45 شارع الهرم، الجيزة",
        "phone": "01155998822"
      },
      {
        "id": 3,
        "name": "بنك القاهرة - فرع بورسعيد",
        "address": "شارع الجمهورية، بورسعيد",
        "phone": "0663456789"
      },
      {
        "id": 4,
        "name": "شركة النجم للشحن والنقل",
        "address": "78 شارع الصناعة، مدينة السادات",
        "phone": "0155776699"
      },
      {
        "id": 5,
        "name": "مروة عبد العزيز فرج",
        "address": "33 شارع الأزهر، الفيوم",
        "phone": "01244887766"
      },
      {
        "id": 6,
        "name": "شركة الحماية للتأمين",
        "address": "المهندسين، الجيزة",
        "phone": "0233556677"
      }
    ],
    "cases": [
      {
        "id": 1,
        "clientId": 1,
        "opponentId": 1,
        "clientCapacity": "مدعي",
        "opponentCapacity": "مدعى عليه",
        "caseNumber": "2156",
        "caseYear": "2025",
        "court": "محكمة طنطا الابتدائية",
        "circuitNumber": "3 مدني",
        "caseType": "مدني",
        "subject": "إخلاء شقة مؤجرة",
        "caseStatus": "متداولة",
        "poaNumber": "122/ب لسنه 2025",
        "appealNumber": "118",
        "appealYear": "2026",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "1",
        "isArchived": false,
        "notes": "مطالبة بالإخلاء لعدم سداد الإيجار"
      },
      {
        "id": 2,
        "clientId": 1,
        "opponentId": 2,
        "clientCapacity": "مستأنف",
        "opponentCapacity": "مستأنف ضده",
        "caseNumber": "7781",
        "caseYear": "2025",
        "court": "محكمة طنطا الابتدائية",
        "circuitNumber": "7 مدني",
        "caseType": "مدني",
        "subject": "مطالبة مالية",
        "caseStatus": "متداولة",
        "poaNumber": "305/أ لسنه 2025",
        "appealNumber": "245",
        "appealYear": "2026",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "2",
        "isArchived": false,
        "notes": "مطالبة بمبلغ مستحق نظير عقد خدمات"
      },
      {
        "id": 3,
        "clientId": 1,
        "opponentId": 3,
        "clientCapacity": "شاكي",
        "opponentCapacity": "مشكو في حقه",
        "caseNumber": "450",
        "caseYear": "2024",
        "court": "محكمة جنح بورسعيد",
        "circuitNumber": "3 جنح",
        "caseType": "جنح",
        "subject": "محضر تبديد منقولات",
        "caseStatus": "متداولة",
        "poaNumber": "77/ج لسنه 2024",
        "appealNumber": "67",
        "appealYear": "2026",
        "cassationNumber": "13",
        "cassationYear": "2026",
        "fileNumber": "3",
        "isArchived": false,
        "notes": "طلب رفع الحجز على حساب بنكي"
      },

      {
        "id": 4,
        "clientId": 2,
        "opponentId": 4,
        "clientCapacity": "مستأنف",
        "opponentCapacity": "مستأنف ضده",
        "caseNumber": "3421",
        "caseYear": "2025",
        "court": "محكمة كفر الشيخ الابتدائية",
        "circuitNumber": "1 مدني",
        "caseType": "مدني",
        "subject": "استئناف حكم تعويض",
        "caseStatus": "متداولة",
        "poaNumber": "410/ب لسنه 2025",
        "appealNumber": "311",
        "appealYear": "2026",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "4",
        "isArchived": false,
        "notes": "استئناف حكم تعويض صادر ضد الموكل"
      },
      {
        "id": 5,
        "clientId": 2,
        "opponentId": 4,
        "clientCapacity": "مدعي",
        "opponentCapacity": "مدعى عليه",
        "caseNumber": "9921",
        "caseYear": "2025",
        "court": "محكمة كفر الشيخ الابتدائية",
        "circuitNumber": "4 تجاري",
        "caseType": "تجاري",
        "subject": "مطالبة بقيمة شحن",
        "caseStatus": "متداولة",
        "poaNumber": "18/د لسنه 2025",
        "appealNumber": "",
        "appealYear": "",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "5",
        "isArchived": false,
        "notes": "مطالبة بقيمة شحن متأخر لنفس الخصم"
      },

      {
        "id": 6,
        "clientId": 3,
        "opponentId": 5,
        "clientCapacity": "متهم",
        "opponentCapacity": "مجني عليه",
        "caseNumber": "6060",
        "caseYear": "2023",
        "court": "محكمة جنح العاشر من رمضان",
        "circuitNumber": "2 جنح",
        "caseType": "جنائي",
        "subject": "جنحة إيصال أمانة",
        "caseStatus": "متداولة",
        "poaNumber": "900/أ لسنه 2023",
        "appealNumber": "90",
        "appealYear": "2026",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "6",
        "isArchived": false,
        "notes": "نزاع على توريد بضاعة وطلبات تعويض"
      },

      {
        "id": 7,
        "clientId": 4,
        "opponentId": 6,
        "clientCapacity": "مدعي",
        "opponentCapacity": "مدعى عليه",
        "caseNumber": "1188",
        "caseYear": "2025",
        "court": "محكمة المنصورة الابتدائية",
        "circuitNumber": "2 مدني",
        "caseType": "مدني",
        "subject": "تعويض حادث",
        "caseStatus": "متداولة",
        "poaNumber": "56/ب لسنه 2025",
        "appealNumber": "",
        "appealYear": "",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "7",
        "isArchived": false,
        "notes": "مطالبة تأمين وتعويض عن حادث"
      },
      {
        "id": 8,
        "clientId": 5,
        "opponentId": 2,
        "clientCapacity": "مدعي",
        "opponentCapacity": "مدعى عليه",
        "caseNumber": "220",
        "caseYear": "2024",
        "court": "محكمة الإسماعيلية الابتدائية",
        "circuitNumber": "9 مدني",
        "caseType": "مدني",
        "subject": "إثبات ملكية",
        "caseStatus": "متداولة",
        "poaNumber": "201/هـ لسنه 2024",
        "appealNumber": "",
        "appealYear": "",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "8",
        "isArchived": false,
        "notes": "دعوى إثبات ملكية على عقار"
      },
      {
        "id": 9,
        "clientId": 6,
        "opponentId": 1,
        "clientCapacity": "مستأنف",
        "opponentCapacity": "مستأنف ضده",
        "caseNumber": "77",
        "caseYear": "2022",
        "court": "محكمة بورسعيد الابتدائية",
        "circuitNumber": "1 مدني",
        "caseType": "مدني",
        "subject": "فسخ عقد إيجار",
        "caseStatus": "منتهية",
        "poaNumber": "15/أ لسنه 2022",
        "appealNumber": "55",
        "appealYear": "2023",
        "cassationNumber": "19",
        "cassationYear": "2024",
        "fileNumber": "9",
        "isArchived": true,
        "notes": "قضية منتهية للأرشفة"
      },
      {
        "id": 10,
        "clientId": 7,
        "opponentId": 2,
        "clientCapacity": "مدعي",
        "opponentCapacity": "مدعى عليه",
        "caseNumber": "9001",
        "caseYear": "2026",
        "court": "محكمة القاهرة الابتدائية",
        "circuitNumber": "5 مدني",
        "caseType": "مدني",
        "subject": "مطالبة مالية",
        "caseStatus": "متداولة",
        "poaNumber": "88/ب لسنه 2026",
        "appealNumber": "",
        "appealYear": "",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "10",
        "isArchived": false,
        "notes": "قضية تجريبية للموكل الجديد لاختبار كل الحقول"
      },
      {
        "id": 11,
        "clientId": 8,
        "opponentId": 1,
        "clientCapacity": "مدعي",
        "opponentCapacity": "مدعى عليه",
        "caseNumber": "5100",
        "caseYear": "2026",
        "court": "محكمة شمال القاهرة الابتدائية",
        "circuitNumber": "8 مدني",
        "caseType": "مدني",
        "subject": "فسخ عقد بيع",
        "caseStatus": "متداولة",
        "poaNumber": "101/س لسنه 2026",
        "appealNumber": "",
        "appealYear": "",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "11",
        "isArchived": false,
        "notes": "قضية مضافة لاختبار بيانات موكل جديد وربطها بالحسابات والجلسات"
      },
      {
        "id": 12,
        "clientId": 9,
        "opponentId": 5,
        "clientCapacity": "مدعى عليه",
        "opponentCapacity": "مدعي",
        "caseNumber": "5101",
        "caseYear": "2026",
        "court": "محكمة الزقازيق الابتدائية",
        "circuitNumber": "3 تجاري",
        "caseType": "تجاري",
        "subject": "مطالبة بقيمة بضاعة",
        "caseStatus": "متداولة",
        "poaNumber": "102/س لسنه 2026",
        "appealNumber": "",
        "appealYear": "",
        "cassationNumber": "",
        "cassationYear": "",
        "fileNumber": "12",
        "isArchived": false,
        "notes": "قضية تجريبية لموكل جديد مع بيانات متكاملة في باقي الجداول"
      }
    ],
    "sessions": [
      {
        "id": 1,
        "clientId": 1,
        "caseId": 1,
        "sessionDate": "2026-04-22",
        "sessionTime": "10:00",
        "court": "محكمة طنطا الابتدائية",
        "sessionType": "مرافعة",
        "roll": "12",
        "inventoryNumber": "101",
        "inventoryYear": "2025",
        "decision": "تأجيل لإعلان الخصم",
        "requests": "إثبات إعلان",
        "notes": "أول جلسة"
      },
      {
        "id": 2,
        "clientId": 1,
        "caseId": 1,
        "sessionDate": "2026-04-24",
        "sessionTime": "11:30",
        "court": "محكمة طنطا الابتدائية",
        "sessionType": "مستندات",
        "roll": "12",
        "inventoryNumber": "101",
        "inventoryYear": "2025",
        "decision": "ضم المستندات وتأجيل",
        "requests": "ضم عقد الإيجار",
        "notes": "تقديم مستندات"
      },

      {
        "id": 3,
        "clientId": 1,
        "caseId": 2,
        "sessionDate": "2026-04-23",
        "sessionTime": "09:30",
        "court": "محكمة طنطا الابتدائية",
        "sessionType": "مرافعة",
        "roll": "6",
        "inventoryNumber": "202",
        "inventoryYear": "2025",
        "decision": "تأجيل للمرافعة",
        "requests": "طلب إلزام بالسداد",
        "notes": "جلسة مرافعة"
      },
      {
        "id": 4,
        "clientId": 1,
        "caseId": 2,
        "sessionDate": "2026-04-26",
        "sessionTime": "10:30",
        "court": "محكمة طنطا الابتدائية",
        "sessionType": "مستندات",
        "roll": "6",
        "inventoryNumber": "202",
        "inventoryYear": "2025",
        "decision": "ضم إيصال سداد جزئي",
        "requests": "ضم إيصال",
        "notes": "مستندات"
      },
      {
        "id": 5,
        "clientId": 1,
        "caseId": 2,
        "sessionDate": "2026-05-01",
        "sessionTime": "12:00",
        "court": "محكمة طنطا الابتدائية",
        "sessionType": "حكم",
        "roll": "6",
        "inventoryNumber": "202",
        "inventoryYear": "2025",
        "decision": "حجز للحكم",
        "requests": "مرافعة ختامية",
        "notes": "قبل النطق بالحكم"
      },

      {
        "id": 6,
        "clientId": 1,
        "caseId": 3,
        "sessionDate": "2026-04-25",
        "sessionTime": "13:00",
        "court": "محكمة بورسعيد الابتدائية",
        "sessionType": "طلب",
        "roll": "18",
        "inventoryNumber": "33",
        "inventoryYear": "2026",
        "decision": "تأجيل لتقديم إفادة البنك",
        "requests": "ضم إفادة",
        "notes": "جلسة واحدة مبدئية"
      },

      {
        "id": 7,
        "clientId": 2,
        "caseId": 4,
        "sessionDate": "2026-04-27",
        "sessionTime": "10:00",
        "court": "محكمة كفر الشيخ الابتدائية",
        "sessionType": "مرافعة",
        "roll": "8",
        "inventoryNumber": "77",
        "inventoryYear": "2025",
        "decision": "تأجيل لإعلان",
        "requests": "إعلان صحيح",
        "notes": "جلسة أولى"
      },
      {
        "id": 8,
        "clientId": 2,
        "caseId": 4,
        "sessionDate": "2026-04-30",
        "sessionTime": "11:00",
        "court": "محكمة كفر الشيخ الابتدائية",
        "sessionType": "مستندات",
        "roll": "8",
        "inventoryNumber": "77",
        "inventoryYear": "2025",
        "decision": "ضم المستندات وتأجيل",
        "requests": "ضم تقرير",
        "notes": "مستندات"
      },

      {
        "id": 9,
        "clientId": 2,
        "caseId": 5,
        "sessionDate": "2026-04-28",
        "sessionTime": "09:45",
        "court": "محكمة كفر الشيخ الابتدائية",
        "sessionType": "مرافعة",
        "roll": "14",
        "inventoryNumber": "88",
        "inventoryYear": "2025",
        "decision": "تأجيل للمرافعة",
        "requests": "تقديم فواتير",
        "notes": "نفس الخصم - قضية مختلفة"
      },
      {
        "id": 10,
        "clientId": 2,
        "caseId": 5,
        "sessionDate": "2026-05-01",
        "sessionTime": "12:15",
        "court": "محكمة كفر الشيخ الابتدائية",
        "sessionType": "مستندات",
        "roll": "14",
        "inventoryNumber": "88",
        "inventoryYear": "2025",
        "decision": "ضم المستندات وتأجيل",
        "requests": "ضم سند شحن",
        "notes": "متابعة"
      },

      {
        "id": 11,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-04-22",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مرافعة",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "تأجيل للإعلان",
        "requests": "إعلان",
        "notes": "1 من 11"
      },
      {
        "id": 12,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-04-23",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مستندات",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "ضم مستندات وتأجيل",
        "requests": "ضم فواتير",
        "notes": "2 من 11"
      },
      {
        "id": 13,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-04-24",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "خبرة",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "تعيين خبير",
        "requests": "طلب خبرة",
        "notes": "3 من 11"
      },
      {
        "id": 14,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-04-25",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مناقشة تقرير",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "تأجيل للمرافعة",
        "requests": "ملاحظات على التقرير",
        "notes": "4 من 11"
      },
      {
        "id": 15,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-04-26",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مرافعة",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "تأجيل",
        "requests": "مرافعة",
        "notes": "5 من 11"
      },
      {
        "id": 16,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-04-27",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مستندات",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "ضم مستندات",
        "requests": "ضم مراسلات",
        "notes": "6 من 11"
      },
      {
        "id": 17,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-04-28",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مرافعة",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "حجز للحكم",
        "requests": "طلبات ختامية",
        "notes": "7 من 11"
      },
      {
        "id": 18,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-04-29",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "حكم",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "إعادة فتح باب المرافعة",
        "requests": "",
        "notes": "8 من 11"
      },
      {
        "id": 19,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-04-30",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مرافعة",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "تأجيل",
        "requests": "مرافعة إضافية",
        "notes": "9 من 11"
      },
      {
        "id": 20,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-05-01",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "مرافعة",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "حجز للحكم",
        "requests": "",
        "notes": "10 من 11"
      },
      {
        "id": 21,
        "clientId": 3,
        "caseId": 6,
        "sessionDate": "2026-05-01",
        "sessionTime": "10:00",
        "court": "محكمة العاشر من رمضان الابتدائية",
        "sessionType": "حكم",
        "roll": "3",
        "inventoryNumber": "12",
        "inventoryYear": "2026",
        "decision": "الحكم للموكل",
        "requests": "استخراج صيغة تنفيذية",
        "notes": "11 من 11"
      },

      {
        "id": 22,
        "clientId": 4,
        "caseId": 7,
        "sessionDate": "2026-04-29",
        "sessionTime": "09:30",
        "court": "محكمة المنصورة الابتدائية",
        "sessionType": "مرافعة",
        "roll": "25",
        "inventoryNumber": "301",
        "inventoryYear": "2026",
        "decision": "تأجيل",
        "requests": "ضم تقرير",
        "notes": ""
      },
      {
        "id": 23,
        "clientId": 5,
        "caseId": 8,
        "sessionDate": "2026-04-30",
        "sessionTime": "11:00",
        "court": "محكمة الإسماعيلية الابتدائية",
        "sessionType": "مرافعة",
        "roll": "7",
        "inventoryNumber": "401",
        "inventoryYear": "2026",
        "decision": "تأجيل",
        "requests": "",
        "notes": ""
      },
      {
        "id": 24,
        "clientId": 7,
        "caseId": 10,
        "sessionDate": "2026-04-22",
        "sessionTime": "09:30",
        "court": "محكمة القاهرة الابتدائية",
        "sessionType": "مرافعة",
        "roll": "5",
        "inventoryNumber": "501",
        "inventoryYear": "2026",
        "decision": "تأجيل لإعلان الخصم",
        "requests": "إعلان صحيح",
        "notes": "1 من 8"
      },
      {
        "id": 25,
        "clientId": 7,
        "caseId": 10,
        "sessionDate": "2026-04-23",
        "sessionTime": "10:00",
        "court": "محكمة القاهرة الابتدائية",
        "sessionType": "مستندات",
        "roll": "5",
        "inventoryNumber": "501",
        "inventoryYear": "2026",
        "decision": "ضم مستندات وتأجيل",
        "requests": "ضم إيصالات",
        "notes": "2 من 8"
      },
      {
        "id": 26,
        "clientId": 7,
        "caseId": 10,
        "sessionDate": "2026-04-24",
        "sessionTime": "11:00",
        "court": "محكمة القاهرة الابتدائية",
        "sessionType": "طلب",
        "roll": "5",
        "inventoryNumber": "501",
        "inventoryYear": "2026",
        "decision": "تأجيل لتقديم مذكرة",
        "requests": "تقديم مذكرة",
        "notes": "3 من 8"
      },
      {
        "id": 27,
        "clientId": 7,
        "caseId": 10,
        "sessionDate": "2026-04-25",
        "sessionTime": "12:00",
        "court": "محكمة القاهرة الابتدائية",
        "sessionType": "خبرة",
        "roll": "5",
        "inventoryNumber": "501",
        "inventoryYear": "2026",
        "decision": "ندب خبير",
        "requests": "طلب خبرة",
        "notes": "4 من 8"
      },
      {
        "id": 28,
        "clientId": 7,
        "caseId": 10,
        "sessionDate": "2026-04-26",
        "sessionTime": "09:45",
        "court": "محكمة القاهرة الابتدائية",
        "sessionType": "مناقشة تقرير",
        "roll": "5",
        "inventoryNumber": "501",
        "inventoryYear": "2026",
        "decision": "تأجيل للمرافعة",
        "requests": "ملاحظات على التقرير",
        "notes": "5 من 8"
      },
      {
        "id": 29,
        "clientId": 7,
        "caseId": 10,
        "sessionDate": "2026-04-27",
        "sessionTime": "10:30",
        "court": "محكمة القاهرة الابتدائية",
        "sessionType": "مرافعة",
        "roll": "5",
        "inventoryNumber": "501",
        "inventoryYear": "2026",
        "decision": "تأجيل",
        "requests": "مرافعة",
        "notes": "6 من 8"
      },
      {
        "id": 30,
        "clientId": 7,
        "caseId": 10,
        "sessionDate": "2026-04-29",
        "sessionTime": "11:30",
        "court": "محكمة القاهرة الابتدائية",
        "sessionType": "مستندات",
        "roll": "5",
        "inventoryNumber": "501",
        "inventoryYear": "2026",
        "decision": "ضم مستندات",
        "requests": "ضم إفادة",
        "notes": "7 من 8"
      },
      {
        "id": 31,
        "clientId": 7,
        "caseId": 10,
        "sessionDate": "2026-05-01",
        "sessionTime": "12:15",
        "court": "محكمة القاهرة الابتدائية",
        "sessionType": "حكم",
        "roll": "5",
        "inventoryNumber": "501",
        "inventoryYear": "2026",
        "decision": "حجز للحكم",
        "requests": "مرافعة ختامية",
        "notes": "8 من 8"
      },
      {
        "id": 32,
        "clientId": 8,
        "caseId": 11,
        "sessionDate": "2026-04-28",
        "sessionTime": "09:30",
        "court": "محكمة شمال القاهرة الابتدائية",
        "sessionType": "مرافعة",
        "roll": "18",
        "inventoryNumber": "611",
        "inventoryYear": "2026",
        "decision": "تأجيل",
        "requests": "تقديم أصل العقد",
        "notes": "جلسة أولى للموكل الجديد (8)"
      },
      {
        "id": 33,
        "clientId": 8,
        "caseId": 11,
        "sessionDate": "2026-04-30",
        "sessionTime": "10:45",
        "court": "محكمة شمال القاهرة الابتدائية",
        "sessionType": "مستندات",
        "roll": "18",
        "inventoryNumber": "611",
        "inventoryYear": "2026",
        "decision": "ضم مستندات",
        "requests": "ضم إيصال سداد",
        "notes": "جلسة مستندات للموكل الجديد (8)"
      },
      {
        "id": 34,
        "clientId": 9,
        "caseId": 12,
        "sessionDate": "2026-04-29",
        "sessionTime": "12:00",
        "court": "محكمة الزقازيق الابتدائية",
        "sessionType": "مرافعة",
        "roll": "6",
        "inventoryNumber": "712",
        "inventoryYear": "2026",
        "decision": "تأجيل لإعلان",
        "requests": "إثبات إعلان",
        "notes": "جلسة أولى للموكل الجديد (9)"
      },
      {
        "id": 35,
        "clientId": 9,
        "caseId": 12,
        "sessionDate": "2026-05-01",
        "sessionTime": "09:15",
        "court": "محكمة الزقازيق الابتدائية",
        "sessionType": "مستندات",
        "roll": "6",
        "inventoryNumber": "712",
        "inventoryYear": "2026",
        "decision": "ضم المستندات وتأجيل",
        "requests": "ضم فواتير",
        "notes": "جلسة مستندات للموكل الجديد (9)"
      }
    ],
    "administrative": [
      {
        "id": 1,
        "clientId": 1,
        "task": "تحضير ملف القضية وتجميع المستندات",
        "dueDate": "2026-04-22",
        "completed": false,
        "location": "مكتب المحاماة",
        "notes": "مطلوب تجهيز ملف القضية قبل جلسة الغد",
        "assignedTo": "السكرتارية"
      },
      {
        "id": 2,
        "clientId": 2,
        "task": "متابعة إعلان الخصم (شركة النجم للشحن)",
        "dueDate": "2026-04-23",
        "completed": false,
        "location": "قلم المحضرين",
        "notes": "التأكد من تمام الإعلان وتسليم الإيصال",
        "assignedTo": "المحامي"
      },
      {
        "id": 3,
        "clientId": 3,
        "task": "متابعة تقرير الخبرة ومراجعة الملاحظات",
        "dueDate": "2026-04-24",
        "completed": false,
        "location": "مكتب الخبير",
        "notes": "استلام نسخة من التقرير ومراجعة البنود",
        "assignedTo": "المحامي"
      },
      {
        "id": 4,
        "clientId": 4,
        "task": "مراجعة مطالبة التأمين وتجهيز مذكرة",
        "dueDate": "2026-04-27",
        "completed": false,
        "location": "مكتب المحاماة",
        "notes": "تجهيز مذكرة مختصرة وطلب ضم مستندات",
        "assignedTo": "المحامي"
      },
      {
        "id": 5,
        "clientId": null,
        "task": "جرد المواعيد وإرسال تذكير بالجلسات",
        "dueDate": "2026-04-22",
        "completed": true,
        "location": "مكتب المحاماة",
        "notes": "تم إرسال التذكيرات",
        "assignedTo": "السكرتارية"
      },
      {
        "id": 6,
        "clientId": 7,
        "task": "مراجعة مستندات الموكل الجديد وتجهيز ملف الدعوى",
        "dueDate": "2026-04-23",
        "completed": false,
        "location": "مكتب المحاماة",
        "notes": "عمل إداري تجريبي مرتبط بالموكل الجديد",
        "assignedTo": "السكرتارية"
      },
      {
        "id": 7,
        "clientId": 8,
        "task": "مراجعة المستندات وتجهيز صحيفة الدعوى",
        "dueDate": "2026-04-28",
        "completed": false,
        "location": "مكتب المحاماة",
        "notes": "متابعة مستندات الموكل الجديد (8) قبل الجلسة",
        "assignedTo": "السكرتارية"
      },
      {
        "id": 8,
        "clientId": 9,
        "task": "متابعة إعلان الخصم وتجهيز مذكرة مختصرة",
        "dueDate": "2026-04-29",
        "completed": false,
        "location": "قلم المحضرين",
        "notes": "إجراء إداري للموكل الجديد (9) مرتبط بالقضية",
        "assignedTo": "المحامي"
      }
    ],
    "accounts": [
      {
        "id": 1,
        "clientId": 1,
        "caseId": 1,
        "paymentDate": "2026-04-22",
        "totalFees": 1500,
        "paidFees": 800,
        "expenses": 65,
        "remaining": 700,
        "notes": "دفعة مقدمة + مصروفات إعلان",
        "payments": [
          {
            "accountId": 1,
            "clientId": 1,
            "caseId": 1,
            "amount": 300,
            "paymentDate": "2026-04-22",
            "createdAt": "2026-04-22T09:15:00.000Z"
          },
          {
            "accountId": 1,
            "clientId": 1,
            "caseId": 1,
            "amount": 500,
            "paymentDate": "2026-04-22",
            "createdAt": "2026-04-22T10:00:00.000Z"
          }
        ],
        "createdAt": "2026-04-22T09:15:00.000Z",
        "updatedAt": "2026-04-22T09:15:00.000Z"
      },
      {
        "id": 2,
        "clientId": 1,
        "caseId": 2,
        "paymentDate": "2026-04-24",
        "totalFees": 2200,
        "paidFees": 1200,
        "expenses": 110,
        "remaining": 1000,
        "notes": "سداد جزء من الأتعاب + مصروفات جلسة",
        "payments": [
          {
            "accountId": 2,
            "clientId": 1,
            "caseId": 2,
            "amount": 500,
            "paymentDate": "2026-04-23",
            "createdAt": "2026-04-23T11:20:00.000Z"
          },
          {
            "accountId": 2,
            "clientId": 1,
            "caseId": 2,
            "amount": 400,
            "paymentDate": "2026-04-24",
            "createdAt": "2026-04-24T12:30:00.000Z"
          },
          {
            "accountId": 2,
            "clientId": 1,
            "caseId": 2,
            "amount": 300,
            "paymentDate": "2026-04-26",
            "createdAt": "2026-04-26T09:40:00.000Z"
          }
        ],
        "createdAt": "2026-04-24T12:30:00.000Z",
        "updatedAt": "2026-04-24T12:30:00.000Z"
      },
      {
        "id": 3,
        "clientId": 2,
        "caseId": 4,
        "paymentDate": "2026-04-27",
        "totalFees": 1800,
        "paidFees": 600,
        "expenses": 90,
        "remaining": 1200,
        "notes": "تم سداد دفعة أولى",
        "payments": [
          {
            "accountId": 3,
            "clientId": 2,
            "caseId": 4,
            "amount": 300,
            "paymentDate": "2026-04-27",
            "createdAt": "2026-04-27T08:10:00.000Z"
          },
          {
            "accountId": 3,
            "clientId": 2,
            "caseId": 4,
            "amount": 300,
            "paymentDate": "2026-04-30",
            "createdAt": "2026-04-30T08:40:00.000Z"
          }
        ],
        "createdAt": "2026-04-27T08:40:00.000Z",
        "updatedAt": "2026-04-27T08:40:00.000Z"
      },
      {
        "id": 4,
        "clientId": 3,
        "caseId": 6,
        "paymentDate": "2026-04-23",
        "totalFees": 3000,
        "paidFees": 1500,
        "expenses": 250,
        "remaining": 1500,
        "notes": "تجهيز ملف خبرة + انتقالات",
        "payments": [
          {
            "accountId": 4,
            "clientId": 3,
            "caseId": 6,
            "amount": 1000,
            "paymentDate": "2026-04-23",
            "createdAt": "2026-04-23T16:00:00.000Z"
          },
          {
            "accountId": 4,
            "clientId": 3,
            "caseId": 6,
            "amount": 500,
            "paymentDate": "2026-04-26",
            "createdAt": "2026-04-26T10:00:00.000Z"
          }
        ],
        "createdAt": "2026-04-23T10:00:00.000Z",
        "updatedAt": "2026-04-23T10:00:00.000Z"
      },
      {
        "id": 5,
        "clientId": 4,
        "caseId": 7,
        "paymentDate": "2026-04-29",
        "totalFees": 1600,
        "paidFees": 400,
        "expenses": 50,
        "remaining": 1200,
        "notes": "دفعة مقدمة",
        "payments": [
          {
            "accountId": 5,
            "clientId": 4,
            "caseId": 7,
            "amount": 250,
            "paymentDate": "2026-04-29",
            "createdAt": "2026-04-29T12:10:00.000Z"
          },
          {
            "accountId": 5,
            "clientId": 4,
            "caseId": 7,
            "amount": 150,
            "paymentDate": "2026-05-01",
            "createdAt": "2026-05-01T09:45:00.000Z"
          }
        ],
        "createdAt": "2026-04-29T09:45:00.000Z",
        "updatedAt": "2026-04-29T09:45:00.000Z"
      },
      {
        "id": 6,
        "clientId": 5,
        "caseId": 8,
        "paymentDate": "2026-04-30",
        "totalFees": 1400,
        "paidFees": 700,
        "expenses": 30,
        "remaining": 700,
        "notes": "تم سداد نصف الأتعاب",
        "payments": [
          {
            "accountId": 6,
            "clientId": 5,
            "caseId": 8,
            "amount": 400,
            "paymentDate": "2026-04-30",
            "createdAt": "2026-04-30T10:05:00.000Z"
          },
          {
            "accountId": 6,
            "clientId": 5,
            "caseId": 8,
            "amount": 300,
            "paymentDate": "2026-05-01",
            "createdAt": "2026-05-01T11:20:00.000Z"
          }
        ],
        "createdAt": "2026-04-30T11:20:00.000Z",
        "updatedAt": "2026-04-30T11:20:00.000Z"
      },
      {
        "id": 7,
        "clientId": 6,
        "caseId": 9,
        "paymentDate": "2026-05-01",
        "totalFees": 1200,
        "paidFees": 1200,
        "expenses": 0,
        "remaining": 0,
        "notes": "قضية منتهية/أتعاب مسددة",
        "payments": [
          {
            "accountId": 7,
            "clientId": 6,
            "caseId": 9,
            "amount": 600,
            "paymentDate": "2026-04-30",
            "createdAt": "2026-04-30T15:10:00.000Z"
          },
          {
            "accountId": 7,
            "clientId": 6,
            "caseId": 9,
            "amount": 600,
            "paymentDate": "2026-05-01",
            "createdAt": "2026-05-01T13:10:00.000Z"
          }
        ],
        "createdAt": "2026-05-01T13:10:00.000Z",
        "updatedAt": "2026-05-01T13:10:00.000Z"
      },
      {
        "id": 8,
        "clientId": 2,
        "caseId": 5,
        "paymentDate": "2026-05-01",
        "totalFees": 900,
        "paidFees": 200,
        "expenses": 35,
        "remaining": 700,
        "notes": "فتح حساب جديد للقضية + مصروفات بسيطة",
        "payments": [
          {
            "accountId": 8,
            "clientId": 2,
            "caseId": 5,
            "amount": 200,
            "paymentDate": "2026-05-01",
            "createdAt": "2026-05-01T13:30:00.000Z"
          }
        ],
        "createdAt": "2026-05-01T13:30:00.000Z",
        "updatedAt": "2026-05-01T13:30:00.000Z"
      },
      {
        "id": 9,
        "clientId": 1,
        "caseId": 3,
        "paymentDate": "2026-04-25",
        "totalFees": 600,
        "paidFees": 100,
        "expenses": 0,
        "remaining": 500,
        "notes": "حساب بدون سداد لسه",
        "payments": [
          {
            "accountId": 9,
            "clientId": 1,
            "caseId": 3,
            "amount": 100,
            "paymentDate": "2026-04-25",
            "createdAt": "2026-04-25T10:40:00.000Z"
          }
        ],
        "createdAt": "2026-04-25T10:10:00.000Z",
        "updatedAt": "2026-04-25T10:10:00.000Z"
      },
      {
        "id": 10,
        "clientId": 4,
        "caseId": 7,
        "paymentDate": "2026-05-01",
        "totalFees": 800,
        "paidFees": 300,
        "expenses": 25,
        "remaining": 500,
        "notes": "دفعة تانية على نفس القضية",
        "payments": [
          {
            "accountId": 10,
            "clientId": 4,
            "caseId": 7,
            "amount": 300,
            "paymentDate": "2026-05-01",
            "createdAt": "2026-05-01T14:05:00.000Z"
          }
        ],
        "createdAt": "2026-05-01T14:05:00.000Z",
        "updatedAt": "2026-05-01T14:05:00.000Z"
      },
      {
        "id": 11,
        "clientId": 6,
        "caseId": 9,
        "paymentDate": "2026-04-26",
        "totalFees": 500,
        "paidFees": 100,
        "expenses": 10,
        "remaining": 400,
        "notes": "مصاريف انتقالات + دفعة بسيطة",
        "payments": [
          {
            "accountId": 11,
            "clientId": 6,
            "caseId": 9,
            "amount": 100,
            "paymentDate": "2026-04-26",
            "createdAt": "2026-04-26T09:50:00.000Z"
          }
        ],
        "createdAt": "2026-04-26T09:50:00.000Z",
        "updatedAt": "2026-04-26T09:50:00.000Z"
      },
      {
        "id": 12,
        "clientId": 5,
        "caseId": 8,
        "paymentDate": "2026-05-01",
        "totalFees": 700,
        "paidFees": 700,
        "expenses": 0,
        "remaining": 0,
        "notes": "إقفال الحساب (مسدد بالكامل)",
        "payments": [
          {
            "accountId": 12,
            "clientId": 5,
            "caseId": 8,
            "amount": 700,
            "paymentDate": "2026-05-01",
            "createdAt": "2026-05-01T16:20:00.000Z"
          }
        ],
        "createdAt": "2026-05-01T16:20:00.000Z",
        "updatedAt": "2026-05-01T16:20:00.000Z"
      },
      {
        "id": 13,
        "clientId": 7,
        "caseId": 10,
        "paymentDate": "2026-04-22",
        "totalFees": 2500,
        "paidFees": 700,
        "expenses": 75,
        "remaining": 1800,
        "notes": "حساب تجريبي للموكل الجديد + مصروفات",
        "payments": [
          {
            "accountId": 13,
            "clientId": 7,
            "caseId": 10,
            "amount": 500,
            "paymentDate": "2026-04-22",
            "createdAt": "2026-04-22T10:05:00.000Z"
          },
          {
            "accountId": 13,
            "clientId": 7,
            "caseId": 10,
            "amount": 200,
            "paymentDate": "2026-04-25",
            "createdAt": "2026-04-25T11:05:00.000Z"
          }
        ],
        "createdAt": "2026-04-22T10:05:00.000Z",
        "updatedAt": "2026-04-22T10:05:00.000Z"
      },
      {
        "id": 14,
        "clientId": 8,
        "caseId": 11,
        "paymentDate": "2026-04-30",
        "totalFees": 2000,
        "paidFees": 900,
        "expenses": 80,
        "remaining": 1100,
        "notes": "دفعات تجريبية للموكل الجديد (8) + مصروفات",
        "payments": [
          {
            "accountId": 14,
            "clientId": 8,
            "caseId": 11,
            "amount": 500,
            "paymentDate": "2026-04-28",
            "createdAt": "2026-04-28T09:20:00.000Z"
          },
          {
            "accountId": 14,
            "clientId": 8,
            "caseId": 11,
            "amount": 400,
            "paymentDate": "2026-04-30",
            "createdAt": "2026-04-30T11:10:00.000Z"
          }
        ],
        "createdAt": "2026-04-28T09:20:00.000Z",
        "updatedAt": "2026-04-30T11:10:00.000Z"
      },
      {
        "id": 15,
        "clientId": 9,
        "caseId": 12,
        "paymentDate": "2026-05-01",
        "totalFees": 1600,
        "paidFees": 600,
        "expenses": 60,
        "remaining": 1000,
        "notes": "حساب تجريبي للموكل الجديد (9) + مصروفات",
        "payments": [
          {
            "accountId": 15,
            "clientId": 9,
            "caseId": 12,
            "amount": 300,
            "paymentDate": "2026-04-29",
            "createdAt": "2026-04-29T12:30:00.000Z"
          },
          {
            "accountId": 15,
            "clientId": 9,
            "caseId": 12,
            "amount": 300,
            "paymentDate": "2026-05-01",
            "createdAt": "2026-05-01T10:25:00.000Z"
          }
        ],
        "createdAt": "2026-04-29T12:30:00.000Z",
        "updatedAt": "2026-05-01T10:25:00.000Z"
      }
    ],
    "accountPayments": [],
    "expertSessions": [
      {
        "id": 1,
        "clientId": 3,
        "caseNumber": "6060/2023",
        "sessionType": "معاينة",
        "status": "مجدولة",
        "sessionDate": "2026-04-24",
        "sessionTime": "12:00",
        "expertName": "م/ أحمد حسني",
        "outgoingNumber": "15",
        "incomingNumber": "22",
        "notes": "معاينة موقع النزاع وإعداد محضر" 
      },
      {
        "id": 2,
        "clientId": 3,
        "caseNumber": "6060/2023",
        "sessionType": "تقديم مستندات",
        "status": "تمت",
        "sessionDate": "2026-04-23",
        "sessionTime": "11:00",
        "expertName": "م/ أحمد حسني",
        "outgoingNumber": "16",
        "incomingNumber": "23",
        "notes": "تم تسليم صور المستندات للخبير" 
      },
      {
        "id": 3,
        "clientId": 1,
        "caseNumber": "2156/2025",
        "sessionType": "مناقشة",
        "status": "مجدولة",
        "sessionDate": "2026-04-26",
        "sessionTime": "10:30",
        "expertName": "د/ محمد عبد السلام",
        "outgoingNumber": "17",
        "incomingNumber": "24",
        "notes": "مناقشة نقاط النزاع أمام الخبير" 
      },
      {
        "id": 4,
        "clientId": 2,
        "caseNumber": "3421/2025",
        "sessionType": "تقرير خبير",
        "status": "تمت",
        "sessionDate": "2026-04-30",
        "sessionTime": "14:00",
        "expertName": "د/ نهى السيد",
        "outgoingNumber": "18",
        "incomingNumber": "25",
        "notes": "استلام نسخة من تقرير الخبرة" 
      },
      {
        "id": 5,
        "clientId": 4,
        "caseNumber": "1188/2025",
        "sessionType": "أخرى",
        "status": "ملغية",
        "sessionDate": "2026-04-29",
        "sessionTime": "09:00",
        "expertName": "م/ خالد طه",
        "outgoingNumber": "19",
        "incomingNumber": "26",
        "notes": "تم الإلغاء لعدم حضور الخصم" 
      },
      {
        "id": 6,
        "clientId": 7,
        "caseNumber": "9001/2026",
        "sessionType": "تقديم مستندات",
        "status": "مجدولة",
        "sessionDate": "2026-04-25",
        "sessionTime": "13:00",
        "expertName": "د/ سامح إبراهيم",
        "outgoingNumber": "20",
        "incomingNumber": "27",
        "notes": "جلسة خبراء تجريبية للموكل الجديد" 
      },
      {
        "id": 7,
        "clientId": 8,
        "caseNumber": "5100/2026",
        "sessionType": "معاينة",
        "status": "مجدولة",
        "sessionDate": "2026-04-28",
        "sessionTime": "15:00",
        "expertName": "م/ شريف أحمد",
        "outgoingNumber": "21",
        "incomingNumber": "28",
        "notes": "جلسة خبراء مضافة للموكل الجديد (8)" 
      },
      {
        "id": 8,
        "clientId": 9,
        "caseNumber": "5101/2026",
        "sessionType": "تقديم مستندات",
        "status": "مجدولة",
        "sessionDate": "2026-04-30",
        "sessionTime": "11:30",
        "expertName": "د/ منى عبد الله",
        "outgoingNumber": "22",
        "incomingNumber": "29",
        "notes": "جلسة خبراء مضافة للموكل الجديد (9)" 
      }
    ],
    "clerkPapers": [
      {
        "id": 1,
        "clientId": 1,
        "caseId": 1,
        "paperType": "إعلان",
        "paperNumber": "2156/2025",
        "clerkOffice": "قلم محضري طنطا",
        "deliveryDate": "2026-04-22",
        "receiptDate": "2026-04-24",
        "notes": "تم تسليم الإعلان للخصم"
      },
      {
        "id": 2,
        "clientId": 2,
        "caseId": 4,
        "paperType": "إنذار",
        "paperNumber": "3421/2025",
        "clerkOffice": "قلم محضري كفر الشيخ",
        "deliveryDate": "2026-04-27",
        "receiptDate": "2026-04-30",
        "notes": "إنذار على يد محضر بخصوص المديونية"
      },
      {
        "id": 3,
        "clientId": 3,
        "caseId": 6,
        "paperType": "إعلان",
        "paperNumber": "6060/2023",
        "clerkOffice": "قلم محضري العاشر من رمضان",
        "deliveryDate": "2026-04-23",
        "receiptDate": "2026-04-24",
        "notes": "إعلان موعد الخبرة"
      },
      {
        "id": 4,
        "clientId": 4,
        "caseId": 7,
        "paperType": "أخرى",
        "paperNumber": "1188/2025",
        "clerkOffice": "قلم محضري المنصورة",
        "deliveryDate": "2026-04-29",
        "receiptDate": "",
        "notes": "جارٍ متابعة الاستلام"
      },
      {
        "id": 5,
        "clientId": 5,
        "caseId": 8,
        "paperType": "إنذار",
        "paperNumber": "220/2024",
        "clerkOffice": "قلم محضري الإسماعيلية",
        "deliveryDate": "2026-04-30",
        "receiptDate": "2026-05-01",
        "notes": "تم الإنذار وتم استلام أصل الورقة"
      },
      {
        "id": 6,
        "clientId": 7,
        "caseId": 10,
        "paperType": "إعلان",
        "paperNumber": "9001/2026",
        "clerkOffice": "قلم محضري مدينة نصر",
        "deliveryDate": "2026-04-22",
        "receiptDate": "2026-04-23",
        "notes": "ورقة قلم كتاب تجريبية للموكل الجديد"
      },
      {
        "id": 7,
        "clientId": 8,
        "caseId": 11,
        "paperType": "إعلان",
        "paperNumber": "5100/2026",
        "clerkOffice": "قلم محضري شمال القاهرة",
        "deliveryDate": "2026-04-28",
        "receiptDate": "2026-04-30",
        "notes": "ورقة قلم كتاب مضافة للموكل الجديد (8)"
      },
      {
        "id": 8,
        "clientId": 9,
        "caseId": 12,
        "paperType": "إنذار",
        "paperNumber": "5101/2026",
        "clerkOffice": "قلم محضري الزقازيق",
        "deliveryDate": "2026-04-29",
        "receiptDate": "2026-05-01",
        "notes": "ورقة قلم كتاب مضافة للموكل الجديد (9)"
      }
    ]
  }
};
